# Generated by Django 4.1.6 on 2023-05-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(choices=[('noble hawk', 'Noble Hawk'), ('eel river', 'Eel River'), ('brookwood', 'Brookwood')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('ScoresId', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Hole1', models.CharField(max_length=2)),
                ('Hole2', models.CharField(max_length=2)),
                ('Hole3', models.CharField(max_length=2)),
                ('Hole4', models.CharField(max_length=2)),
                ('Hole5', models.CharField(max_length=2)),
                ('Hole6', models.CharField(max_length=2)),
                ('Hole7', models.CharField(max_length=2)),
                ('Hole8', models.CharField(max_length=2)),
                ('Hole9', models.CharField(max_length=2)),
                ('Hole10', models.CharField(max_length=2)),
                ('Hole11', models.CharField(max_length=2)),
                ('Hole12', models.CharField(max_length=2)),
                ('Hole13', models.CharField(max_length=2)),
                ('Hole14', models.CharField(max_length=2)),
                ('Hole15', models.CharField(max_length=2)),
                ('Hole16', models.CharField(max_length=2)),
                ('Hole17', models.CharField(max_length=2)),
                ('Hole18', models.CharField(max_length=2)),
            ],
        ),
    ]
